packages:
  - 'packages/*'

allowBuilds:
  '@nestjs/core': false
  better-sqlite3: true
  electron: true
  esbuild: false

onlyBuiltDependencies:
  - '@nestjs/core'
  - 'better-sqlite3'
  - 'electron'
  - 'esbuild'
