// 框架关键词表（按语言）+ 服务端框架依赖关键词（form-detector 后端形态原始信号用）。
// 独立文件：数据表较大，避免 language-map.ts 超出单文件纯 LOC 上限。

import type { LanguageId } from './types';

/** 框架关键词：name = 展示名，keywords = 依赖名前缀命中。 */
export interface FrameworkKeyword {
  readonly name: string;
  readonly keywords: readonly string[];
}

export const FRAMEWORK_KEYWORDS: Readonly<Record<LanguageId, readonly FrameworkKeyword[]>> = {
  javascript: [
    { name: 'Next.js', keywords: ['next'] },
    { name: 'NestJS', keywords: ['@nestjs/core', '@nestjs/common'] },
    { name: 'React', keywords: ['react', 'react-dom', '@reduxjs/toolkit'] },
    { name: 'Vue', keywords: ['vue', '@vue/cli-service', 'vue-router'] },
    { name: 'Angular', keywords: ['@angular/core'] },
    { name: 'Express', keywords: ['express'] },
    { name: 'Fastify', keywords: ['fastify'] },
    { name: 'Koa', keywords: ['koa'] },
    { name: 'Svelte', keywords: ['svelte', '@sveltejs/kit'] },
    { name: 'Nuxt', keywords: ['nuxt', 'nuxt3'] },
    { name: 'Remix', keywords: ['@remix-run/react'] },
    { name: 'Gatsby', keywords: ['gatsby'] },
    { name: 'Taro', keywords: ['@tarojs/cli', '@tarojs/taro'] },
    { name: 'React Native', keywords: ['react-native'] },
    { name: 'Electron', keywords: ['electron'] },
    { name: 'Element Plus', keywords: ['element-plus'] },
    { name: 'Vant', keywords: ['vant'] },
    { name: 'Ant Design', keywords: ['antd', '@ant-design/icons'] },
    { name: 'uni-app', keywords: ['@dcloudio/uni-app', '@dcloudio/vite-plugin-uni'] },
    { name: 'Vitepress', keywords: ['vitepress'] },
    { name: 'Docusaurus', keywords: ['@docusaurus/core'] },
    { name: 'Strapi', keywords: ['@strapi/strapi'] },
  ],
  typescript: [
    { name: 'Next.js', keywords: ['next'] },
    { name: 'NestJS', keywords: ['@nestjs/core', '@nestjs/common'] },
    { name: 'React', keywords: ['react', 'react-dom', '@reduxjs/toolkit'] },
    { name: 'Vue', keywords: ['vue', '@vue/cli-service', 'vue-router'] },
    { name: 'Angular', keywords: ['@angular/core'] },
    { name: 'Express', keywords: ['express'] },
    { name: 'Fastify', keywords: ['fastify'] },
    { name: 'Koa', keywords: ['koa'] },
    { name: 'Svelte', keywords: ['svelte', '@sveltejs/kit'] },
    { name: 'Nuxt', keywords: ['nuxt', 'nuxt3'] },
    { name: 'Remix', keywords: ['@remix-run/react'] },
    { name: 'Gatsby', keywords: ['gatsby'] },
    { name: 'Taro', keywords: ['@tarojs/cli', '@tarojs/taro'] },
    { name: 'React Native', keywords: ['react-native'] },
    { name: 'Electron', keywords: ['electron'] },
    { name: 'Element Plus', keywords: ['element-plus'] },
    { name: 'Vant', keywords: ['vant'] },
    { name: 'Ant Design', keywords: ['antd', '@ant-design/icons'] },
    { name: 'uni-app', keywords: ['@dcloudio/uni-app', '@dcloudio/vite-plugin-uni'] },
    { name: 'Vitepress', keywords: ['vitepress'] },
    { name: 'Docusaurus', keywords: ['@docusaurus/core'] },
    { name: 'Strapi', keywords: ['@strapi/strapi'] },
  ],
  python: [
    { name: 'Django', keywords: ['django'] },
    { name: 'FastAPI', keywords: ['fastapi'] },
    { name: 'Flask', keywords: ['flask'] },
    { name: 'Tornado', keywords: ['tornado'] },
    { name: 'Sanic', keywords: ['sanic'] },
    { name: 'Aiohttp', keywords: ['aiohttp'] },
    { name: 'Streamlit', keywords: ['streamlit'] },
    { name: 'Celery', keywords: ['celery'] },
  ],
  java: [
    { name: 'Spring Boot', keywords: ['spring-boot-starter', 'spring-boot-starter-web', 'spring-boot-starter-security', 'spring-boot-starter-data-jpa', 'spring-boot-starter-validation', 'spring-boot-starter-data-redis', 'spring-boot-starter-amqp', 'spring-boot-starter-actuator'] },
    { name: 'Spring Cloud', keywords: ['spring-cloud-starter-gateway', 'spring-cloud-starter-openfeign', 'spring-cloud-starter'] },
    { name: 'Spring', keywords: ['spring-web', 'spring-webmvc', 'spring-context', 'spring-boot'] },
    { name: 'MyBatis', keywords: ['mybatis', 'mybatis-plus', 'mybatis-spring-boot-starter'] },
    { name: 'Netty', keywords: ['netty-all', 'netty-transport', 'netty-handler'] },
    { name: 'Dubbo', keywords: ['dubbo', 'dubbo-spring-boot-starter'] },
  ],
  go: [
    { name: 'Gin', keywords: ['github.com/gin-gonic/gin'] },
    { name: 'Echo', keywords: ['github.com/labstack/echo'] },
    { name: 'Fiber', keywords: ['github.com/gofiber/fiber/v2'] },
    { name: 'Chi', keywords: ['github.com/go-chi/chi'] },
    { name: 'Beego', keywords: ['github.com/beego/beego'] },
    { name: 'Gorilla', keywords: ['github.com/gorilla/mux'] },
    { name: 'gRPC', keywords: ['google.golang.org/grpc'] },
  ],
  rust: [
    { name: 'Axum', keywords: ['axum'] },
    { name: 'Actix-web', keywords: ['actix-web'] },
    { name: 'Rocket', keywords: ['rocket'] },
    { name: 'Tauri', keywords: ['tauri'] },
    { name: 'Warp', keywords: ['warp'] },
  ],
  php: [
    { name: 'Laravel', keywords: ['laravel/framework', 'laravel'] },
    { name: 'Symfony', keywords: ['symfony/framework-bundle', 'symfony/symfony'] },
    { name: 'ThinkPHP', keywords: ['topthink/framework', 'thinkphp'] },
    { name: 'CodeIgniter', keywords: ['codeigniter4/framework', 'codeigniter/framework'] },
    { name: 'Slim', keywords: ['slim/slim'] },
  ],
  ruby: [
    { name: 'Rails', keywords: ['rails'] },
    { name: 'Sinatra', keywords: ['sinatra'] },
    { name: 'Grape', keywords: ['grape'] },
  ],
  csharp: [],
  kotlin: [],
  swift: [],
  c: [],
  cpp: [],
  dart: [],
  shell: [],
};

/** 服务端框架依赖关键词（form-detector 后端形态原始信号用）。 */
export const SERVER_FRAMEWORK_DEP_KEYWORDS: ReadonlySet<string> = new Set([
  'next',
  '@nestjs/core',
  'express',
  'fastify',
  'koa',
  'django',
  'fastapi',
  'flask',
  'tornado',
  'sanic',
  'aiohttp',
  'spring-boot-starter',
  'spring-boot-starter-web',
  'spring-boot-starter-security',
  'spring-boot-starter-data-jpa',
  'spring-web',
  'spring-webmvc',
  'spring-cloud-starter',
  'dubbo',
  'github.com/gin-gonic/gin',
  'github.com/labstack/echo',
  'github.com/gofiber/fiber/v2',
  'github.com/go-chi/chi',
  'github.com/beego/beego',
  'axum',
  'actix-web',
  'rocket',
  'laravel/framework',
  'symfony/framework-bundle',
  'topthink/framework',
  'codeigniter4/framework',
  'slim/slim',
  'rails',
  'sinatra',
]);
