import type { BuiltinRule } from './types';

/**
 * Level 3 降级内置规则（~50 条）
 *
 * 当所有外部工具都失败时使用这些基础规则进行兜底扫描。
 * 规则覆盖三个维度：安全、质量、架构。
 */
export const BUILTIN_FALLBACK_RULES: BuiltinRule[] = [
  // ─── 安全规则 (20) ────────────────────────────────────
  {
    ruleId: 'fallback/security/hardcoded-password',
    severity: 'error',
    category: 'security',
    message: '检测到硬编码密码',
    pattern: 'password\\s*[=:]\\s*["\'](?!\\$|process\\.env|import\\.meta)',
  },
  {
    ruleId: 'fallback/security/hardcoded-api-key',
    severity: 'error',
    category: 'security',
    message: '检测到硬编码 API 密钥',
    pattern: '(api[_-]?key|apikey|secret|token)\\s*[=:]\\s*["\'][A-Za-z0-9_\\-]{16,}',
  },
  {
    ruleId: 'fallback/security/sql-concat',
    severity: 'error',
    category: 'security',
    message: '检测到 SQL 字符串拼接，请使用参数化查询',
    pattern: '(SELECT|INSERT|UPDATE|DELETE).*\\+\\s*(req\\.|body\\.|params\\.|query\\.)',
  },
  {
    ruleId: 'fallback/security/eval-usage',
    severity: 'error',
    category: 'security',
    message: '检测到 eval 调用，存在代码注入风险',
    pattern: '\\beval\\s*\\(',
  },
  {
    ruleId: 'fallback/security/innerhtml',
    severity: 'warning',
    category: 'security',
    message: '检测到 innerHTML 赋值，存在 XSS 风险',
    pattern: '\\.innerHTML\\s*=',
  },
  {
    ruleId: 'fallback/security/no-rate-limit',
    severity: 'warning',
    category: 'security',
    message: 'API 路由未配置速率限制',
    pattern: 'app\\.(get|post|put|delete|patch)\\(',
  },
  {
    ruleId: 'fallback/security/insecure-random',
    severity: 'warning',
    category: 'security',
    message: '使用 Math.random() 做安全敏感操作，请用 crypto.randomBytes',
    pattern: 'Math\\.random\\(',
  },
  {
    ruleId: 'fallback/security/command-injection',
    severity: 'error',
    category: 'security',
    message: '检测到 shell 命令执行，存在命令注入风险',
    pattern: '(exec|spawn|execSync|spawnSync)\\s*\\(\\s*["\']',
  },
  {
    ruleId: 'fallback/security/prototype-pollution',
    severity: 'error',
    category: 'security',
    message: '检测到原型链污染风险',
    pattern: '__proto__|constructor\\.prototype',
  },
  {
    ruleId: 'fallback/security/debug-endpoint',
    severity: 'warning',
    category: 'security',
    message: '生产环境不应暴露调试接口',
    pattern: '(/debug|/__webpack|/sockjs-node)',
  },
  {
    ruleId: 'fallback/security/no-cors',
    severity: 'info',
    category: 'security',
    message: '未配置 CORS 中间件',
    pattern: 'cors\\(',
  },
  {
    ruleId: 'fallback/security/no-helmet',
    severity: 'info',
    category: 'security',
    message: '未检测到 Helmet 安全头中间件',
    pattern: 'helmet\\(',
  },
  {
    ruleId: 'fallback/security/path-traversal',
    severity: 'error',
    category: 'security',
    message: '检测到路径遍历风险，请校验用户输入',
    pattern: 'readFile(Sync)?\\(.*\\+\\s*(req|params|body)',
  },
  {
    ruleId: 'fallback/security/no-tls',
    severity: 'warning',
    category: 'security',
    message: '检测到 HTTP 而非 HTTPS 服务',
    pattern: 'http\\.createServer',
  },
  {
    ruleId: 'fallback/security/insecure-deserialize',
    severity: 'error',
    category: 'security',
    message: '检测到不安全的反序列化操作',
    pattern: 'JSON\\.parse|unserialize|pickle\\.loads',
  },
  {
    ruleId: 'fallback/security/no-csp',
    severity: 'info',
    category: 'security',
    message: '未检测到 Content-Security-Policy 头',
    pattern: 'Content-Security-Policy',
  },
  {
    ruleId: 'fallback/security/console-log-secret',
    severity: 'warning',
    category: 'security',
    message: 'console.log 可能泄露敏感信息',
    pattern: 'console\\.(log|dir|info)\\s*\\(\\s*(password|secret|token|key)',
  },
  {
    ruleId: 'fallback/security/no-auth',
    severity: 'error',
    category: 'security',
    message: '检测到未认证的修改操作',
    pattern: 'app\\.(post|put|delete|patch)\\(["\']/',
  },
  {
    ruleId: 'fallback/security/sensitive-files',
    severity: 'warning',
    category: 'security',
    message: '检测到敏感文件被包含',
    pattern: '(\\.env|\\.pem|\\.key|credentials\\.json|config\\.yml)',
  },
  {
    ruleId: 'fallback/security/no-https-redirect',
    severity: 'warning',
    category: 'security',
    message: '未强制 HTTPS 重定向',
    pattern: 'https\\:',
  },

  // ─── 质量规则 (18) ─────────────────────────────────────
  {
    ruleId: 'fallback/quality/console-log',
    severity: 'warning',
    category: 'quality',
    message: '生产代码中不应包含 console.log',
    pattern: 'console\\.(log|debug|trace)\\(',
  },
  {
    ruleId: 'fallback/quality/debugger',
    severity: 'error',
    category: 'quality',
    message: '生产代码中不应包含 debugger 语句',
    pattern: '\\bdebugger\\b',
  },
  {
    ruleId: 'fallback/quality/todo-comment',
    severity: 'info',
    category: 'quality',
    message: '存在 TODO 待办项',
    pattern: '\\bTODO\\b|\\bFIXME\\b|\\bHACK\\b|\\bXXX\\b',
  },
  {
    ruleId: 'fallback/quality/empty-catch',
    severity: 'warning',
    category: 'quality',
    message: '空的 catch 块会隐藏错误',
    pattern: 'catch\\s*\\([^)]*\\)\\s*\\{\\s*\\}',
  },
  {
    ruleId: 'fallback/quality/duplicate-key',
    severity: 'error',
    category: 'quality',
    message: '对象中存在重复键',
    pattern: '(\\w+):\\s*[^,]+,\\s*\\1:',
  },
  {
    ruleId: 'fallback/quality/missing-fallthrough',
    severity: 'warning',
    category: 'quality',
    message: 'switch case 缺少 break，可能意外贯穿',
    pattern: 'case\\s+[^:]+:\\s*\\n(?!\\s*break)',
  },
  {
    ruleId: 'fallback/quality/var-usage',
    severity: 'warning',
    category: 'quality',
    message: '使用 var 而非 const/let',
    pattern: '\\bvar\\s+',
  },
  {
    ruleId: 'fallback/quality/eqeqeq',
    severity: 'warning',
    category: 'quality',
    message: '使用 == 而非 ===，可能导致类型转换',
    pattern: '==\\s[^=]|==\\n',
  },
  {
    ruleId: 'fallback/quality/no-null-comparison',
    severity: 'info',
    category: 'quality',
    message: '使用 foo == null 而非 foo === null || foo === undefined',
    pattern: '===\\s*null|!==\\s*null',
  },
  {
    ruleId: 'fallback/quality/async-without-await',
    severity: 'warning',
    category: 'quality',
    message: 'async 函数中未使用 await',
    pattern: 'async\\s+function\\s+\\w+\\s*\\([^)]*\\)\\s*\\{\\s*(?!await)',
  },
  {
    ruleId: 'fallback/quality/for-in-without-hasown',
    severity: 'warning',
    category: 'quality',
    message: 'for...in 未使用 hasOwnProperty 检查',
    pattern: 'for\\s*\\(\\s*(var|let|const)\\s+\\w+\\s+in\\s+',
  },
  {
    ruleId: 'fallback/quality/no-barrel-import',
    severity: 'info',
    category: 'quality',
    message: '从 barrel (index) 文件导入可能导致循环依赖',
    pattern: "from\\s+['\"]\\.\\.?/[^'\"]*/index['\"]",
  },
  {
    ruleId: 'fallback/quality/large-function',
    severity: 'info',
    category: 'quality',
    message: '函数过长，建议拆分为多个小函数',
    pattern: '',
  },
  {
    ruleId: 'fallback/quality/complex-condition',
    severity: 'info',
    category: 'quality',
    message: '条件表达式过于复杂，建议提取为变量',
    pattern: '&&.*\\|\\|.*&&\\|\\|.*\\|\\|.*&&',
  },
  {
    ruleId: 'fallback/quality/nested-callback',
    severity: 'info',
    category: 'quality',
    message: '嵌套回调过深，建议使用 async/await',
    pattern: '',
  },
  {
    ruleId: 'fallback/quality/magic-number',
    severity: 'info',
    category: 'quality',
    message: '检测到魔术数字，建议定义为常量',
    pattern: '',
  },
  {
    ruleId: 'fallback/quality/type-any',
    severity: 'warning',
    category: 'quality',
    message: '使用 any 类型会失去类型检查保护',
    pattern: ':\\s*any\\b',
  },
  {
    ruleId: 'fallback/quality/no-unused-variable',
    severity: 'warning',
    category: 'quality',
    message: '检测到未使用的变量',
    pattern: '',
  },

  // ─── 架构规则 (12) ─────────────────────────────────────
  {
    ruleId: 'fallback/architecture/circular-dependency',
    severity: 'error',
    category: 'architecture',
    message: '检测到循环依赖',
    pattern: '',
  },
  {
    ruleId: 'fallback/architecture/layer-violation',
    severity: 'error',
    category: 'architecture',
    message: '业务层不应直接引用数据访问层',
    pattern: '',
  },
  {
    ruleId: 'fallback/architecture/no-entity-in-controller',
    severity: 'warning',
    category: 'architecture',
    message: 'Controller 不应直接引用 Entity',
    pattern: '',
  },
  {
    ruleId: 'fallback/architecture/no-domain-in-infra',
    severity: 'warning',
    category: 'architecture',
    message: '基础设施层不应依赖领域层',
    pattern: '',
  },
  {
    ruleId: 'fallback/architecture/cyclic-import',
    severity: 'error',
    category: 'architecture',
    message: '模块间存在循环导入',
    pattern: '',
  },
  {
    ruleId: 'fallback/architecture/utils-everywhere',
    severity: 'info',
    category: 'architecture',
    message: 'utils 工具函数分散在各模块，建议统一管理',
    pattern: '',
  },
  {
    ruleId: 'fallback/architecture/no-service-in-view',
    severity: 'warning',
    category: 'architecture',
    message: '视图层不应直接调用 Service',
    pattern: '',
  },
  {
    ruleId: 'fallback/architecture/global-state',
    severity: 'warning',
    category: 'architecture',
    message: '检测到全局状态/单例模式滥用',
    pattern: '',
  },
  {
    ruleId: 'fallback/architecture/missing-abstraction',
    severity: 'info',
    category: 'architecture',
    message: '模块缺少接口抽象，不利于测试和扩展',
    pattern: '',
  },
  {
    ruleId: 'fallback/architecture/layer-skip',
    severity: 'warning',
    category: 'architecture',
    message: '跳层调用：跨过中间层直接调用底层模块',
    pattern: '',
  },
  {
    ruleId: 'fallback/architecture/fat-controller',
    severity: 'info',
    category: 'architecture',
    message: 'Controller 过于臃肿，逻辑应移至 Service',
    pattern: '',
  },
  {
    ruleId: 'fallback/architecture/no-dto-in-entity',
    severity: 'warning',
    category: 'architecture',
    message: 'Entity 不应依赖 DTO',
    pattern: '',
  },
];
