import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import * as fs from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';
import { execFile, execFileSync } from 'node:child_process';
import { promisify } from 'node:util';
import type { ProjectProfile } from '@zh/dependency';
import { AiOriginDetectorImpl, classifyStrength, commitEvidenceFromLog, isAiMarkedCommit } from '../ai-code/origin-detector';
import { analyzeStyleSignature } from '../ai-code/style-signature';
import type { AiEvidence } from '../ai-code/types';

const execFileAsync = promisify(execFile);

let hasGit = true;
try {
  execFileSync('git', ['--version'], { stdio: 'ignore' });
} catch {
  hasGit = false;
}

function profile(projectPath: string): ProjectProfile {
  return { projectPath, language: 'typescript', framework: null, packageManager: 'pnpm', hasTypeScript: true };
}

function evidence(kind: AiEvidence['kind'], confidence: number): AiEvidence {
  return { kind, detail: 'd', confidence };
}

describe('commitEvidenceFromLog', () => {
  it('解析 git log 输出为提交证据（首行头 + 后续文件行，空行分隔提交）', () => {
    const output = [
      `Alice\x1f1712345600\x1ffeat: init\x1fabc1234`,
      `src/index.ts`,
      ``,
      `Bob\x1f1712346000\x1ffeat: generated by copilot\x1fdef5678`,
      `src/app.ts`,
    ].join('\n');

    const commits = commitEvidenceFromLog(output);
    expect(commits).toHaveLength(2);
    expect(commits[0]?.author).toBe('Alice');
    expect(commits[0]?.files).toEqual(['src/index.ts']);
    expect(commits[1]?.subject).toBe('feat: generated by copilot');
    expect(commits[1]?.hash).toBe('def5678');
    expect(commits[1]?.files).toEqual(['src/app.ts']);
  });

  it('空输出 / 损坏行 → 空数组（git 降级不抛错）', () => {
    expect(commitEvidenceFromLog('')).toHaveLength(0);
    expect(commitEvidenceFromLog('garbage-line\n\n')).toHaveLength(0);
  });
});

describe('isAiMarkedCommit', () => {
  it('AI 工具标记命中 / 未命中', () => {
    expect(isAiMarkedCommit('feat: generated by copilot')).toBe(true);
    expect(isAiMarkedCommit('feat: gpt-4 refactor')).toBe(true);
    expect(isAiMarkedCommit('fix: typo in docs')).toBe(false);
  });
});

describe('classifyStrength', () => {
  it('user-tagged → strong（唯一确定性信号）', () => {
    expect(classifyStrength([evidence('user-tagged', 1)])).toBe('strong');
  });

  it('多类证据一致 → strong', () => {
    expect(classifyStrength([evidence('commit-meta', 0.7), evidence('style-signature', 0.9)])).toBe('strong');
  });

  it('commit-meta 单类 → suggestive', () => {
    expect(classifyStrength([evidence('commit-meta', 0.7)])).toBe('suggestive');
  });

  it('tool-report 单类 → suggestive', () => {
    expect(classifyStrength([evidence('tool-report', 0.6)])).toBe('suggestive');
  });

  it('高置信风格 → suggestive；单弱风格 → uncertain', () => {
    expect(classifyStrength([evidence('style-signature', 0.9)])).toBe('suggestive');
    expect(classifyStrength([evidence('style-signature', 0.5)])).toBe('uncertain');
  });

  it('≥2 弱风格组合 → suggestive', () => {
    expect(classifyStrength([evidence('style-signature', 0.4), evidence('style-signature', 0.5)])).toBe('suggestive');
  });
});

describe('analyzeStyleSignature', () => {
  it('comment-marker：AI 工具典型注释', () => {
    const signals = analyzeStyleSignature('// generated by copilot\nconst a = 1;\n');
    expect(signals.some((s) => s.kind === 'comment-marker' && s.confidence === 0.9)).toBe(true);
  });

  it('mixed-indent：≥2 种显著缩进宽度且少数派 ≥25%', () => {
    const lines: string[] = ['const top = 1;'];
    for (let i = 0; i < 12; i++) lines.push(`  const a${i} = 1;`);
    for (let i = 0; i < 12; i++) lines.push(`    const b${i} = 1;`);
    const signals = analyzeStyleSignature(lines.join('\n'));
    expect(signals.some((s) => s.kind === 'mixed-indent')).toBe(true);
  });

  it('templated-naming：≥2 个带序号基名', () => {
    const content = [
      'const item1 = 1;',
      'const item2 = 2;',
      'const step1 = 3;',
      'const step2 = 4;',
      'const query1 = 5;',
      'const query2 = 6;',
    ].join('\n');
    const signals = analyzeStyleSignature(content);
    expect(signals.some((s) => s.kind === 'templated-naming')).toBe(true);
  });

  it('普通代码 → 无信号', () => {
    expect(analyzeStyleSignature('const a = 1;\nexport default a;\n')).toHaveLength(0);
  });
});

describe('AiOriginDetectorImpl', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'zh-ai-origin-'));
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  async function writeFile(rel: string, content: string): Promise<void> {
    const abs = path.join(tmpDir, rel);
    await fs.mkdir(path.dirname(abs), { recursive: true });
    await fs.writeFile(abs, content);
  }

  it.skipIf(!hasGit)('commit 标记 + 风格突变 → strong（证据可展开）', async () => {
    await execFileAsync('git', ['init', '-q', tmpDir]);
    await execFileAsync('git', ['-C', tmpDir, 'config', 'user.email', 't@example.com']);
    await execFileAsync('git', ['-C', tmpDir, 'config', 'user.name', 'T']);
    await writeFile('src/foo.ts', '// generated by copilot\nconst x = 1;\n');
    await execFileAsync('git', ['-C', tmpDir, 'add', '-A']);
    await execFileAsync('git', ['-C', tmpDir, 'commit', '-q', '-m', 'feat: generated by copilot']);

    const findings = await new AiOriginDetectorImpl().detect(profile(tmpDir));

    expect(findings).toHaveLength(1);
    const finding = findings[0];
    expect(finding?.file).toBe('src/foo.ts');
    expect(finding?.strength).toBe('strong');
    const kinds = finding?.evidence.map((e) => e.kind);
    expect(kinds).toContain('commit-meta');
    expect(kinds).toContain('style-signature');
  });

  it('单弱风格特征 → 默认不标记；includeUncertain 时输出 uncertain', async () => {
    await writeFile('src/foo.ts', 'const item1 = 1;\nconst item2 = 2;\nconst step1 = 3;\nconst step2 = 4;\n');

    const detector = new AiOriginDetectorImpl();
    expect(await detector.detect(profile(tmpDir))).toHaveLength(0);

    const withUncertain = await detector.detect(profile(tmpDir), { includeUncertain: true });
    expect(withUncertain).toHaveLength(1);
    expect(withUncertain[0]?.strength).toBe('uncertain');
  });

  it('user-tagged + tool-report 输入被聚合', async () => {
    await writeFile('src/a.ts', 'export const a = 1;\n');
    await writeFile('src/b.ts', 'export const b = 2;\n');

    const findings = await new AiOriginDetectorImpl().detect(profile(tmpDir), {
      userTags: [{ file: 'src/a.ts', source: 'claude-code' }],
      toolReports: [{ file: 'src/b.ts', detail: 'copilot suggestion applied' }],
    });

    expect(findings).toHaveLength(2);
    expect(findings[0]?.strength).toBe('strong');
    expect(findings[0]?.file).toBe('src/a.ts');
    expect(findings[1]?.file).toBe('src/b.ts');
  });
});
